// mockData.js
// Houses placeholder data for universities, the signed-in user's profile, and their applications.
export const universities = [
  {
    id: 'tum',
    name: 'Technical University of Munich',
    country: 'Germany',
    city: 'Munich',
    fields: ['Engineering', 'Computer Science', 'Natural Sciences'],
    language: 'English & German',
    languages: ['English', 'German'],
    tuitionEUR: { min: 0, max: 2500 },
    ranking: 36,
    deadlines: [
      { label: 'Winter 2025', date: '2025-07-15' },
      { label: 'Summer 2026', date: '2025-12-01' },
    ],
    entryCriteria: [
      { label: 'GPA', value: '≥ 2.0 / 4.0 or 7.0 / 10' },
      { label: 'Language', value: 'IELTS 6.5 or German B2' },
      { label: 'Portfolio', value: 'Motivation letter & resume' },
    ],
    programs: [
      { name: 'BSc Computer Science', degree: 'BSc' },
      { name: 'BSc Mechanical Engineering', degree: 'BSc' },
      { name: 'BSc Sustainable Management', degree: 'BSc' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/1d4ed8/ffffff&text=TUM',
  },
  {
    id: 'tu-delft',
    name: 'Delft University of Technology',
    country: 'Netherlands',
    city: 'Delft',
    fields: ['Engineering', 'Design', 'Architecture'],
    language: 'English',
    languages: ['English'],
    tuitionEUR: { min: 6500, max: 8600 },
    ranking: 49,
    deadlines: [
      { label: 'Regular 2025', date: '2025-01-15' },
      { label: 'Late 2025', date: '2025-04-01' },
    ],
    entryCriteria: [
      { label: 'GPA', value: '≥ 3.0 / 4.0' },
      { label: 'Language', value: 'IELTS 6.5 or TOEFL 92' },
      { label: 'Documents', value: 'Portfolio for design programs' },
    ],
    programs: [
      { name: 'BSc Aerospace Engineering', degree: 'BSc' },
      { name: 'BSc Industrial Design Engineering', degree: 'BSc' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/0ea5e9/ffffff&text=TUD',
  },
  {
    id: 'sorbonne',
    name: 'Sorbonne University',
    country: 'France',
    city: 'Paris',
    fields: ['Humanities', 'Sciences', 'Medicine'],
    language: 'French & English',
    languages: ['French', 'English'],
    tuitionEUR: { min: 280, max: 3000 },
    ranking: 60,
    deadlines: [
      { label: 'Licence 2025', date: '2025-05-31' },
      { label: 'Medicine 2025', date: '2025-03-15' },
    ],
    entryCriteria: [
      { label: 'GPA', value: '≥ 12/20 French scale' },
      { label: 'Language', value: 'DELF B2 or IELTS 6.0' },
      { label: 'Essays', value: 'Motivation letter & CV' },
    ],
    programs: [
      { name: 'Licence Lettres Modernes', degree: 'BA' },
      { name: 'BSc Physics', degree: 'BSc' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/f97316/ffffff&text=SU',
  },
  {
    id: 'lund',
    name: 'Lund University',
    country: 'Sweden',
    city: 'Lund',
    fields: ['Engineering', 'Life Sciences', 'Social Sciences'],
    language: 'English & Swedish',
    languages: ['English', 'Swedish'],
    tuitionEUR: { min: 9500, max: 12000 },
    ranking: 85,
    deadlines: [
      { label: 'Autumn 2025', date: '2025-01-15' },
      { label: 'Documents deadline', date: '2025-02-01' },
    ],
    entryCriteria: [
      { label: 'GPA', value: '≥ 3.0 / 4.0' },
      { label: 'Language', value: 'IELTS 6.5 or TOEFL 90' },
      { label: 'Extras', value: 'Statement of purpose' },
    ],
    programs: [
      { name: 'BSc Biomedicine', degree: 'BSc' },
      { name: 'BSc International Business', degree: 'BSc' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/7c3aed/ffffff&text=LU',
  },
  {
    id: 'cph',
    name: 'University of Copenhagen',
    country: 'Denmark',
    city: 'Copenhagen',
    fields: ['Life Sciences', 'Sustainability', 'Humanities'],
    language: 'English & Danish',
    languages: ['English', 'Danish'],
    tuitionEUR: { min: 6000, max: 13000 },
    ranking: 103,
    deadlines: [
      { label: 'September 2025', date: '2025-03-15' },
      { label: 'Housing deadline', date: '2025-04-20' },
    ],
    entryCriteria: [
      { label: 'GPA', value: '≥ 6.5 / 10 Danish scale' },
      { label: 'Language', value: 'IELTS 6.5 or TOEFL 88' },
      { label: 'Extras', value: 'Motivation letter optional' },
    ],
    programs: [
      { name: 'BSc Global Health', degree: 'BSc' },
      { name: 'BA European Ethnology', degree: 'BA' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1471623432079-b009d30b6729?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/10b981/ffffff&text=KU',
  },
  {
    id: 'aalto',
    name: 'Aalto University',
    country: 'Finland',
    city: 'Espoo',
    fields: ['Design', 'Business', 'Technology'],
    language: 'English & Finnish',
    languages: ['English', 'Finnish'],
    tuitionEUR: { min: 12000, max: 15000 },
    ranking: 116,
    deadlines: [
      { label: 'First joint application', date: '2025-01-03' },
      { label: 'Supplementary material', date: '2025-01-17' },
    ],
    entryCriteria: [
      { label: 'GPA', value: 'Competitive transcript with maths focus' },
      { label: 'Language', value: 'IELTS 6.5 or TOEFL 92' },
      { label: 'Portfolio', value: 'Required for arts programs' },
    ],
    programs: [
      { name: 'BSc Information Technology', degree: 'BSc' },
      { name: 'Bachelor of Arts in Design', degree: 'BA' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/f43f5e/ffffff&text=AAL',
  },
  {
    id: 'upc',
    name: 'Polytechnic University of Catalonia',
    country: 'Spain',
    city: 'Barcelona',
    fields: ['Engineering', 'Architecture', 'Technology'],
    language: 'Spanish & Catalan',
    languages: ['Spanish', 'Catalan', 'English'],
    tuitionEUR: { min: 2500, max: 4200 },
    ranking: 130,
    deadlines: [
      { label: 'Fall 2025', date: '2025-06-15' },
      { label: 'Scholarship deadline', date: '2025-05-01' },
    ],
    entryCriteria: [
      { label: 'GPA', value: '≥ 7 / 10 Spanish scale' },
      { label: 'Language', value: 'Spanish B2 or IELTS 6.0' },
      { label: 'Extras', value: 'Entrance test for some programs' },
    ],
    programs: [
      { name: 'BSc Telecommunications Engineering', degree: 'BSc' },
      { name: 'BArch Architecture', degree: 'BArch' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/facc15/1f2937&text=UPC',
  },
  {
    id: 'polimi',
    name: 'Politecnico di Milano',
    country: 'Italy',
    city: 'Milan',
    fields: ['Architecture', 'Design', 'Engineering'],
    language: 'Italian & English',
    languages: ['Italian', 'English'],
    tuitionEUR: { min: 3900, max: 3900 },
    ranking: 123,
    deadlines: [
      { label: 'First call 2025', date: '2024-12-18' },
      { label: 'Second call 2025', date: '2025-03-07' },
    ],
    entryCriteria: [
      { label: 'GPA', value: 'Competitive transcript' },
      { label: 'Language', value: 'IELTS 6.0 or Italian B2' },
      { label: 'Portfolio', value: 'Mandatory for design' },
    ],
    programs: [
      { name: 'BSc Architectural Design', degree: 'BSc' },
      { name: 'BSc Computer Engineering', degree: 'BSc' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1529429617124-aee1f8e54f01?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/ef4444/ffffff&text=POLI',
  },
  {
    id: 'tcd',
    name: 'Trinity College Dublin',
    country: 'Ireland',
    city: 'Dublin',
    fields: ['Humanities', 'Computer Science', 'Business'],
    language: 'English',
    languages: ['English'],
    tuitionEUR: { min: 19000, max: 22000 },
    ranking: 81,
    deadlines: [
      { label: 'Early decision', date: '2024-11-01' },
      { label: 'Final deadline', date: '2025-02-01' },
    ],
    entryCriteria: [
      { label: 'GPA', value: '≥ 3.3 / 4.0' },
      { label: 'Language', value: 'IELTS 6.5 or TOEFL 90' },
      { label: 'Extras', value: 'Personal statement & references' },
    ],
    programs: [
      { name: 'BA Philosophy, Political Science, Economics and Sociology', degree: 'BA' },
      { name: 'BSc Computer Science', degree: 'BSc' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/14b8a6/ffffff&text=TCD',
  },
  {
    id: 'tu-vienna',
    name: 'TU Wien',
    country: 'Austria',
    city: 'Vienna',
    fields: ['Engineering', 'Computer Science', 'Mathematics'],
    language: 'German & English',
    languages: ['German', 'English'],
    tuitionEUR: { min: 0, max: 1450 },
    ranking: 191,
    deadlines: [
      { label: 'Winter semester', date: '2025-09-30' },
      { label: 'Summer semester', date: '2025-02-05' },
    ],
    entryCriteria: [
      { label: 'GPA', value: '≥ 2.5 / 4.0' },
      { label: 'Language', value: 'German B2 or IELTS 6.0' },
      { label: 'Extras', value: 'Motivation letter recommended' },
    ],
    programs: [
      { name: 'BSc Electrical Engineering', degree: 'BSc' },
      { name: 'BSc Data Science', degree: 'BSc' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/a855f7/ffffff&text=TUW',
  },
  {
    id: 'ku-leuven',
    name: 'KU Leuven',
    country: 'Belgium',
    city: 'Leuven',
    fields: ['Engineering', 'Bioscience', 'Humanities'],
    language: 'English & Dutch',
    languages: ['English', 'Dutch'],
    tuitionEUR: { min: 980, max: 3500 },
    ranking: 61,
    deadlines: [
      { label: 'EEA applicants', date: '2025-06-01' },
      { label: 'Non-EEA applicants', date: '2025-03-01' },
    ],
    entryCriteria: [
      { label: 'GPA', value: 'Strong maths background for STEM' },
      { label: 'Language', value: 'IELTS 6.5 or TOEFL 86' },
      { label: 'Extras', value: 'Letter of motivation' },
    ],
    programs: [
      { name: 'BSc Engineering Technology', degree: 'BSc' },
      { name: 'BA European Studies', degree: 'BA' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/6366f1/ffffff&text=KUL',
  },
  {
    id: 'porto',
    name: 'University of Porto',
    country: 'Portugal',
    city: 'Porto',
    fields: ['Marine Sciences', 'Engineering', 'Arts'],
    language: 'Portuguese & English',
    languages: ['Portuguese', 'English'],
    tuitionEUR: { min: 1500, max: 3500 },
    ranking: 295,
    deadlines: [
      { label: 'Phase 1 2025', date: '2025-03-20' },
      { label: 'Phase 2 2025', date: '2025-06-30' },
    ],
    entryCriteria: [
      { label: 'GPA', value: 'Secondary diploma with maths focus' },
      { label: 'Language', value: 'Portuguese B1 or IELTS 6.0' },
      { label: 'Extras', value: 'Entrance exam for some faculties' },
    ],
    programs: [
      { name: 'BSc Marine Biology', degree: 'BSc' },
      { name: 'BA Fine Arts', degree: 'BA' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/0ea5e9/ffffff&text=UP',
  },
  {
    id: 'charles',
    name: 'Charles University Prague',
    country: 'Czech Republic',
    city: 'Prague',
    fields: ['Medicine', 'Law', 'Humanities'],
    language: 'Czech & English',
    languages: ['Czech', 'English'],
    tuitionEUR: { min: 3000, max: 12000 },
    ranking: 248,
    deadlines: [
      { label: 'Medicine entrance exam', date: '2025-05-25' },
      { label: 'Humanities deadline', date: '2025-06-30' },
    ],
    entryCriteria: [
      { label: 'GPA', value: 'Strong sciences for medicine' },
      { label: 'Language', value: 'IELTS 6.5 or Czech B2' },
      { label: 'Extras', value: 'Entrance test + interview' },
    ],
    programs: [
      { name: 'MD General Medicine', degree: 'MD' },
      { name: 'BA International Relations', degree: 'BA' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1544986581-efac024faf62?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/f97316/ffffff&text=CU',
  },
  {
    id: 'warsaw',
    name: 'University of Warsaw',
    country: 'Poland',
    city: 'Warsaw',
    fields: ['Economics', 'International Relations', 'Mathematics'],
    language: 'Polish & English',
    languages: ['Polish', 'English'],
    tuitionEUR: { min: 2300, max: 4000 },
    ranking: 284,
    deadlines: [
      { label: 'Bachelor round 1', date: '2025-07-07' },
      { label: 'Bachelor round 2', date: '2025-08-14' },
    ],
    entryCriteria: [
      { label: 'GPA', value: 'High secondary diploma average' },
      { label: 'Language', value: 'IELTS 6.0 or Polish B2' },
      { label: 'Extras', value: 'Entrance exam for select faculties' },
    ],
    programs: [
      { name: 'BA International Relations', degree: 'BA' },
      { name: 'BSc Data Science', degree: 'BSc' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1526128898661-e60820f3d16c?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/22c55e/ffffff&text=UW',
  },
  {
    id: 'uva',
    name: 'University of Amsterdam',
    country: 'Netherlands',
    city: 'Amsterdam',
    fields: ['Media', 'Economics', 'Social Sciences'],
    language: 'English & Dutch',
    languages: ['English', 'Dutch'],
    tuitionEUR: { min: 4500, max: 9500 },
    ranking: 55,
    deadlines: [
      { label: 'Application 2025', date: '2025-01-15' },
      { label: 'Housing priority', date: '2025-04-01' },
    ],
    entryCriteria: [
      { label: 'GPA', value: '≥ 3.0 / 4.0' },
      { label: 'Language', value: 'IELTS 7.0 or TOEFL 100' },
      { label: 'Extras', value: 'Motivation letter & resume' },
    ],
    programs: [
      { name: 'BSc Economics & Business', degree: 'BSc' },
      { name: 'BA Communication Science', degree: 'BA' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1440964829947-ca3277bd37f8?auto=format&fit=crop&w=1600&q=80',
    logo: 'https://dummyimage.com/80x80/ef4444/ffffff&text=UvA',
  },
];

export const userProfile = {
  completedOnboarding: false,
  academics: {
    gpa: 3.4,
    scale: '4.0',
    tests: {
      ielts: 6.5,
      toefl: null,
      sat: 1290,
    },
  },
  preferences: {
    countries: ['Netherlands', 'Germany', 'Sweden', 'Ireland'],
    fields: ['Engineering', 'Computer Science', 'Design'],
    budgetMin: 0,
    budgetMax: 12000,
    languages: ['English', 'German'],
  },
};

export const applications = [
  {
    id: 'app-tum',
    universityId: 'tum',
    status: 'in_progress',
    tasks: [
      { id: 't1', label: 'Request academic transcripts', done: true },
      { id: 't2', label: 'Draft motivation letter', done: false, dueDate: '2025-02-15' },
      { id: 't3', label: 'Book IELTS retake', done: false, dueDate: '2025-01-30' },
    ],
    nextDeadlineDate: '2025-07-15',
  },
  {
    id: 'app-tu-delft',
    universityId: 'tu-delft',
    status: 'submitted',
    tasks: [
      { id: 't1', label: 'Upload transcript', done: true },
      { id: 't2', label: 'Submit application fee', done: true },
      { id: 't3', label: 'Track housing application', done: false, dueDate: '2025-04-05' },
    ],
    nextDeadlineDate: '2025-04-01',
  },
  {
    id: 'app-lund',
    universityId: 'lund',
    status: 'accepted',
    tasks: [
      { id: 't1', label: 'Confirm offer acceptance', done: true },
      { id: 't2', label: 'Pay enrollment deposit', done: true },
      { id: 't3', label: 'Arrange residence permit', done: false, dueDate: '2025-06-01' },
    ],
    nextDeadlineDate: '2025-06-01',
  },
  {
    id: 'app-porto',
    universityId: 'porto',
    status: 'in_progress',
    tasks: [
      { id: 't1', label: 'Translate diploma to Portuguese', done: false, dueDate: '2025-03-01' },
      { id: 't2', label: 'Complete online form', done: false, dueDate: '2025-03-10' },
      { id: 't3', label: 'Schedule visa appointment', done: false },
    ],
    nextDeadlineDate: '2025-03-20',
  },
];
